Eugene branch
RazmikGrygoryan/API pull request #2
Opened 2024-03-27 08:06 UTC by RazmikGrygoryan

2024-03-28 09:21 UTC, eugene-okulik requested changes
В остальном, всё ок. Осталось чуть-чуть ))

2024-03-28 09:21 UTC, eugene-okulik commented on endpoints/__pycache__/endpoint.cpython-311.pyc
Нужно удоалить этот файл и папку `__pycache__`  
Когда будешь запускать тесты, она создастся снова, но уже не полезет в репозиторий.

2024-03-28 09:21 UTC, eugene-okulik commented on endpoints/__pycache__/get_one_meme.cpython-311.pyc
Нужно удоалить этот файл и папку `__pycache__`

2024-03-28 09:21 UTC, eugene-okulik commented on tests/test_memes.py
> +])
Этими данными ты тестируешь один и тот же кейс: ты шлешь в апишку поле, которого там не существует и не шлешь ни одного правильного поля.  
Пэйлоды для параметризации будут выглядеть примерно так:
```python
@pytest.mark.parametrize("invalid_payload", [
    {
        "id": None,
        "text": 1,
        "url": "Meme",
        "tags": ["Meme111"],
        "info": {"Meme": 77777}
    },
    {
        "id": None,
        "text": "Meme111",
        "url": [],
        "tags": ["Meme111"],
        "info": {"Meme": 77777}
    },
    {
        "id": None,
        "text": "Meme111",
        "url": "Meme",
        "tags": ["Meme111"],
        "info": 77777
    },
    {
        "id": None,
        "text": "Meme111",
        "url": "Meme",
        "tags": "Meme111",
        "info": {"Meme": 77777}
    }
])
```

2024-03-28 14:39 UTC, eugene-okulik requested changes
Ты уже добавил папку `__pycache__` в .gitignore  
Но одно это действие не удалит файл из репозитория. Сейчас нужно сделать одно простое действие. Удалить папку `__pycache__` ото всюду, где она создалась и сделать commit. После этого, даже если эта папка снова создастся, она не улетит в репозиторий.

2024-03-29 06:01 UTC, RazmikGrygoryan commented
с репы удалил,до этого в коммите тоже удалял, теперь вроде все норм

2024-03-29 08:31 UTC, eugene-okulik approved these changes
Красота. Ну всё. Можешь мержить ветку main.  
Ну и следующее задание ждет тебя.

2024-03-29 08:53 UTC, merged